api_book_search:
    path: /api/book/search
    controller: App\Controller\BookController::search
    methods: GET

api_book_show:
    path: /api/book/show/{id}
    controller: App\Controller\BookController::show
    methods: GET

api_category:
    path: /api/category
    controller: App\Controller\CategoryController::index
    methods: GET
